name: Build and Release APK
on: [workflow_dispatch]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to latest version

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -so- https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 17  # Updated to LTS version
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # Eclipse Temurin is the new AdoptOpenJDK
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: |
        VERSION=$(grep versionName app/build.gradle | awk -F\" '{print $2}')
        echo "app_version=${VERSION}" >> $GITHUB_OUTPUT

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk Potato-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Game-Unlocker-${{ steps.version.outputs.app_version }}
        path: Potato-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1  # More maintained alternative
      with:
        tag_name: v${{ steps.version.outputs.app_version }}
        name: Potato Unlocker ${{ steps.version.outputs.app_version }}
        body: Automatic release of Potato Unlocker
        prerelease: false
        files: Potato-unlocker-v${{ steps.version.outputs.app_version }}.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
